{% set name = "austin-tui" %}
{% set version = "1.2.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: c1cd322ab5598a7ea98ca50dece1de5ea9e625968ac112d2b3f1db148b283e68

build:
  number: 3
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - sysroot_linux-64 2.17  # [linux64]
  host:
    - pip
    - poetry
    - python
    - hatchling
    - hatch-vcs
  run:
    - austin >=2.0.0
    - austin-python
    - importlib_resources >=2.0.1
    - lxml >=4.5.1
    - python

test:
  commands:
    - austin-tui --help
  requires:
    - pip

about:
  home: https://github.com/P403n1x87/austin-tui
  summary: The top-like text-based user interface for Austin
  license: GPL-3.0-or-later
  license_file: LICENSE.md
  dev_url: https://github.com/P403n1x87/austin-tui
  doc_url: https://github.com/P403n1x87/austin-tui/blob/master/README.md

extra:
  recipe-maintainers:
    - siboehm
    - matthiasdiener
