{% set name = "austin-tui" %}
{% set version = "1.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/austin-tui-{{ version }}.tar.gz
  sha256: 605d1f813627cd023f030a651ecfdf677471020508a56a75bd28dce2517eea18

build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - sysroot_linux-64 2.17  # [linux64]
  host:
    - pip
    - poetry
    - python
  run:
    - austin >=2.0.0
    - austin-python
    - importlib_resources >=2.0.1
    - lxml >=4.5.1
    - python

test:
  commands:
    - austin-tui --help
  requires:
    - pip

about:
  home: https://github.com/P403n1x87/austin-tui
  summary: The top-like text-based user interface for Austin
  license: GPL-3.0-or-later
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - siboehm
